### ISSUE TITLE
Regarding syntax issues

### ISSUE THREAD

**Issue by yliu0715** [CSC59939/QuickBorrow#16]
My commits are changing a lot of the original files (like single quotes to double quotes, and semicolons to colons at the end of the line). This causes merge conflicts and is a waste of time to fix. Should we agree on a styling tool to use? I think @synzen mentioned ESLint before as an option.

**Comment by MicLi01** [comment]
I agree with using a styling tool.

**Comment by JackyLiu97** [comment]
I'll work on the styling issue .
